# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyEtude.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(728, 477)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(728, 0))
        MainWindow.setMaximumSize(QtCore.QSize(728, 620))
        MainWindow.setMouseTracking(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 711, 461))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.genTab = QtWidgets.QWidget()
        self.genTab.setObjectName("genTab")
        self.infoGroupBox = QtWidgets.QGroupBox(self.genTab)
        self.infoGroupBox.setGeometry(QtCore.QRect(10, 10, 321, 371))
        self.infoGroupBox.setObjectName("infoGroupBox")
        self.titreGroupBox = QtWidgets.QGroupBox(self.infoGroupBox)
        self.titreGroupBox.setGeometry(QtCore.QRect(10, 20, 291, 61))
        self.titreGroupBox.setObjectName("titreGroupBox")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.titreGroupBox)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.titreLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.titreLayout.setContentsMargins(0, 0, 0, 0)
        self.titreLayout.setObjectName("titreLayout")
        self.titreLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titreLineEdit.sizePolicy().hasHeightForWidth())
        self.titreLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.titreLineEdit.setFont(font)
        self.titreLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.titreLineEdit.setClearButtonEnabled(True)
        self.titreLineEdit.setObjectName("titreLineEdit")
        self.titreLayout.addWidget(self.titreLineEdit)
        self.soustitreGroupBox = QtWidgets.QGroupBox(self.infoGroupBox)
        self.soustitreGroupBox.setGeometry(QtCore.QRect(10, 80, 291, 61))
        self.soustitreGroupBox.setObjectName("soustitreGroupBox")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.soustitreGroupBox)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.soustitreLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.soustitreLayout.setContentsMargins(0, 0, 0, 0)
        self.soustitreLayout.setObjectName("soustitreLayout")
        self.soustitreLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soustitreLineEdit.sizePolicy().hasHeightForWidth())
        self.soustitreLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.soustitreLineEdit.setFont(font)
        self.soustitreLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.soustitreLineEdit.setClearButtonEnabled(True)
        self.soustitreLineEdit.setObjectName("soustitreLineEdit")
        self.soustitreLayout.addWidget(self.soustitreLineEdit)
        self.matGroupBox = QtWidgets.QGroupBox(self.infoGroupBox)
        self.matGroupBox.setGeometry(QtCore.QRect(80, 150, 171, 61))
        self.matGroupBox.setObjectName("matGroupBox")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.matGroupBox)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.matLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.matLayout.setContentsMargins(0, 0, 0, 0)
        self.matLayout.setObjectName("matLayout")
        self.matLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.matLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matLineEdit.sizePolicy().hasHeightForWidth())
        self.matLineEdit.setSizePolicy(sizePolicy)
        self.matLineEdit.setMinimumSize(QtCore.QSize(0, 29))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.matLineEdit.setFont(font)
        self.matLineEdit.setText("")
        self.matLineEdit.setFrame(True)
        self.matLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.matLineEdit.setClearButtonEnabled(False)
        self.matLineEdit.setObjectName("matLineEdit")
        self.matLayout.addWidget(self.matLineEdit)
        self.matToolButton = QtWidgets.QToolButton(self.matGroupBox)
        self.matToolButton.setGeometry(QtCore.QRect(120, 25, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.matToolButton.setFont(font)
        self.matToolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.matToolButton.setCheckable(False)
        self.matToolButton.setChecked(False)
        self.matToolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.matToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.matToolButton.setAutoRaise(False)
        self.matToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.matToolButton.setObjectName("matToolButton")
        self.numGroupBox = QtWidgets.QGroupBox(self.infoGroupBox)
        self.numGroupBox.setGeometry(QtCore.QRect(80, 210, 171, 61))
        self.numGroupBox.setObjectName("numGroupBox")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.numGroupBox)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.numLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.numLayout.setContentsMargins(0, 0, 0, 0)
        self.numLayout.setObjectName("numLayout")
        self.numLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.numLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLineEdit.sizePolicy().hasHeightForWidth())
        self.numLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.numLineEdit.setFont(font)
        self.numLineEdit.setText("")
        self.numLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.numLineEdit.setClearButtonEnabled(False)
        self.numLineEdit.setObjectName("numLineEdit")
        self.numLayout.addWidget(self.numLineEdit)
        self.numToolButton = QtWidgets.QToolButton(self.numGroupBox)
        self.numToolButton.setGeometry(QtCore.QRect(120, 25, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.numToolButton.setFont(font)
        self.numToolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.numToolButton.setCheckable(False)
        self.numToolButton.setChecked(False)
        self.numToolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.numToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.numToolButton.setAutoRaise(False)
        self.numToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.numToolButton.setObjectName("numToolButton")
        self.sectionGroupBox = QtWidgets.QGroupBox(self.infoGroupBox)
        self.sectionGroupBox.setGeometry(QtCore.QRect(10, 300, 291, 61))
        self.sectionGroupBox.setObjectName("sectionGroupBox")
        self.sectionNumLabel = QtWidgets.QLabel(self.sectionGroupBox)
        self.sectionNumLabel.setGeometry(QtCore.QRect(20, 25, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        font.setUnderline(True)
        self.sectionNumLabel.setFont(font)
        self.sectionNumLabel.setObjectName("sectionNumLabel")
        self.sectionLineEdit = QtWidgets.QLineEdit(self.sectionGroupBox)
        self.sectionLineEdit.setGeometry(QtCore.QRect(40, 21, 241, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionLineEdit.sizePolicy().hasHeightForWidth())
        self.sectionLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        font.setUnderline(True)
        self.sectionLineEdit.setFont(font)
        self.sectionLineEdit.setMaxLength(32767)
        self.sectionLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sectionLineEdit.setClearButtonEnabled(True)
        self.sectionLineEdit.setObjectName("sectionLineEdit")
        self.sectionLineEdit.raise_()
        self.sectionNumLabel.raise_()
        self.pathPathLabel = QtWidgets.QLabel(self.genTab)
        self.pathPathLabel.setGeometry(QtCore.QRect(350, 170, 321, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathPathLabel.sizePolicy().hasHeightForWidth())
        self.pathPathLabel.setSizePolicy(sizePolicy)
        self.pathPathLabel.setMaximumSize(QtCore.QSize(321, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pathPathLabel.setFont(font)
        self.pathPathLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pathPathLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.pathPathLabel.setWordWrap(True)
        self.pathPathLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.pathPathLabel.setObjectName("pathPathLabel")
        self.infoPersoGroupBox = QtWidgets.QGroupBox(self.genTab)
        self.infoPersoGroupBox.setGeometry(QtCore.QRect(350, 10, 319, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoPersoGroupBox.sizePolicy().hasHeightForWidth())
        self.infoPersoGroupBox.setSizePolicy(sizePolicy)
        self.infoPersoGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.infoPersoGroupBox.setObjectName("infoPersoGroupBox")
        self.auteurPersoGroupBox = QtWidgets.QGroupBox(self.infoPersoGroupBox)
        self.auteurPersoGroupBox.setGeometry(QtCore.QRect(10, 20, 291, 61))
        self.auteurPersoGroupBox.setObjectName("auteurPersoGroupBox")
        self.auteurPersoLabel = QtWidgets.QLabel(self.auteurPersoGroupBox)
        self.auteurPersoLabel.setGeometry(QtCore.QRect(10, 20, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(18)
        font.setItalic(True)
        self.auteurPersoLabel.setFont(font)
        self.auteurPersoLabel.setTextFormat(QtCore.Qt.RichText)
        self.auteurPersoLabel.setScaledContents(False)
        self.auteurPersoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.auteurPersoLabel.setObjectName("auteurPersoLabel")
        self.secPersoGroupBox = QtWidgets.QGroupBox(self.infoPersoGroupBox)
        self.secPersoGroupBox.setGeometry(QtCore.QRect(10, 80, 291, 61))
        self.secPersoGroupBox.setObjectName("secPersoGroupBox")
        self.secPersoLabel = QtWidgets.QLabel(self.secPersoGroupBox)
        self.secPersoLabel.setGeometry(QtCore.QRect(10, 20, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(17)
        font.setItalic(True)
        self.secPersoLabel.setFont(font)
        self.secPersoLabel.setTextFormat(QtCore.Qt.RichText)
        self.secPersoLabel.setScaledContents(True)
        self.secPersoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.secPersoLabel.setWordWrap(False)
        self.secPersoLabel.setObjectName("secPersoLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.genTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 400, 661, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.genButtonLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.genButtonLayout.setContentsMargins(0, 0, 0, 0)
        self.genButtonLayout.setObjectName("genButtonLayout")
        self.genPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genPushButton.sizePolicy().hasHeightForWidth())
        self.genPushButton.setSizePolicy(sizePolicy)
        self.genPushButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.genPushButton.setFont(font)
        self.genPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.genPushButton.setObjectName("genPushButton")
        self.genButtonLayout.addWidget(self.genPushButton)
        self.tabWidget.addTab(self.genTab, "")
        self.configTab = QtWidgets.QWidget()
        self.configTab.setObjectName("configTab")
        self.infoPerso = QtWidgets.QGroupBox(self.configTab)
        self.infoPerso.setGeometry(QtCore.QRect(10, 10, 311, 171))
        self.infoPerso.setObjectName("infoPerso")
        self.auteurConfig = QtWidgets.QGroupBox(self.infoPerso)
        self.auteurConfig.setGeometry(QtCore.QRect(10, 30, 291, 61))
        self.auteurConfig.setObjectName("auteurConfig")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.auteurConfig)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.auteurLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.auteurLayout.setContentsMargins(0, 0, 0, 0)
        self.auteurLayout.setObjectName("auteurLayout")
        self.auteurLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auteurLineEdit.sizePolicy().hasHeightForWidth())
        self.auteurLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.auteurLineEdit.setFont(font)
        self.auteurLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.auteurLineEdit.setClearButtonEnabled(True)
        self.auteurLineEdit.setObjectName("auteurLineEdit")
        self.auteurLayout.addWidget(self.auteurLineEdit)
        self.secConfig = QtWidgets.QGroupBox(self.infoPerso)
        self.secConfig.setGeometry(QtCore.QRect(10, 100, 291, 61))
        self.secConfig.setObjectName("secConfig")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.secConfig)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.secLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.secLayout.setContentsMargins(0, 0, 0, 0)
        self.secLayout.setObjectName("secLayout")
        self.secLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secLineEdit.sizePolicy().hasHeightForWidth())
        self.secLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.secLineEdit.setFont(font)
        self.secLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.secLineEdit.setClearButtonEnabled(True)
        self.secLineEdit.setObjectName("secLineEdit")
        self.secLayout.addWidget(self.secLineEdit)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.configTab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(330, 20, 351, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.configSaveLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.configSaveLayout.setContentsMargins(30, 50, 30, 50)
        self.configSaveLayout.setSpacing(0)
        self.configSaveLayout.setObjectName("configSaveLayout")
        self.configSaveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configSaveButton.sizePolicy().hasHeightForWidth())
        self.configSaveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.configSaveButton.setFont(font)
        self.configSaveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.configSaveButton.setObjectName("configSaveButton")
        self.configSaveLayout.addWidget(self.configSaveButton)
        self.matieresConfig = QtWidgets.QGroupBox(self.configTab)
        self.matieresConfig.setGeometry(QtCore.QRect(10, 190, 661, 261))
        self.matieresConfig.setFlat(False)
        self.matieresConfig.setCheckable(True)
        self.matieresConfig.setChecked(False)
        self.matieresConfig.setObjectName("matieresConfig")
        self.matiereTableWidget = QtWidgets.QTableWidget(self.matieresConfig)
        self.matiereTableWidget.setEnabled(True)
        self.matiereTableWidget.setGeometry(QtCore.QRect(10, 30, 641, 191))
        self.matiereTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.matiereTableWidget.setDragEnabled(True)
        self.matiereTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.matiereTableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.matiereTableWidget.setAlternatingRowColors(True)
        self.matiereTableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.matiereTableWidget.setRowCount(0)
        self.matiereTableWidget.setObjectName("matiereTableWidget")
        self.matiereTableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.matiereTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.matiereTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.matiereTableWidget.setHorizontalHeaderItem(2, item)
        self.matiereTableWidget.horizontalHeader().setDefaultSectionSize(175)
        self.matiereTableWidget.horizontalHeader().setStretchLastSection(True)
        self.matiereTableWidget.verticalHeader().setVisible(False)
        self.matiereTableWidget.verticalHeader().setStretchLastSection(False)
        self.matiereTablePlus = QtWidgets.QPushButton(self.matieresConfig)
        self.matiereTablePlus.setEnabled(True)
        self.matiereTablePlus.setGeometry(QtCore.QRect(10, 230, 21, 21))
        self.matiereTablePlus.setObjectName("matiereTablePlus")
        self.matiereTableMinus = QtWidgets.QPushButton(self.matieresConfig)
        self.matiereTableMinus.setEnabled(True)
        self.matiereTableMinus.setGeometry(QtCore.QRect(30, 230, 21, 21))
        self.matiereTableMinus.setObjectName("matiereTableMinus")
        self.matiereTableReset = QtWidgets.QPushButton(self.matieresConfig)
        self.matiereTableReset.setEnabled(True)
        self.matiereTableReset.setGeometry(QtCore.QRect(60, 230, 75, 21))
        self.matiereTableReset.setObjectName("matiereTableReset")
        self.matiereTableBrowse = QtWidgets.QPushButton(self.matieresConfig)
        self.matiereTableBrowse.setEnabled(True)
        self.matiereTableBrowse.setGeometry(QtCore.QRect(577, 230, 75, 21))
        self.matiereTableBrowse.setObjectName("matiereTableBrowse")
        self.tabWidget.addTab(self.configTab, "")
        self.aboutTab = QtWidgets.QWidget()
        self.aboutTab.setObjectName("aboutTab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.aboutTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 681, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.aboutLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.aboutLayout.setContentsMargins(0, 0, 0, 0)
        self.aboutLayout.setObjectName("aboutLayout")
        self.titleLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.titleLabel.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.aboutLayout.addWidget(self.titleLabel)
        self.versionLayout = QtWidgets.QHBoxLayout()
        self.versionLayout.setObjectName("versionLayout")
        self.versionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.versionLabel.setTextFormat(QtCore.Qt.RichText)
        self.versionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.versionLabel.setObjectName("versionLabel")
        self.versionLayout.addWidget(self.versionLabel)
        self.varVersionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.varVersionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.varVersionLabel.setObjectName("varVersionLabel")
        self.versionLayout.addWidget(self.varVersionLabel)
        self.aboutLayout.addLayout(self.versionLayout)
        self.gitHubLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.gitHubLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gitHubLabel.setOpenExternalLinks(True)
        self.gitHubLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.gitHubLabel.setObjectName("gitHubLabel")
        self.aboutLayout.addWidget(self.gitHubLabel)
        self.tabWidget.addTab(self.aboutTab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.infoGroupBox.setTitle(_translate("MainWindow", "Informations"))
        self.titreGroupBox.setTitle(_translate("MainWindow", "Titre"))
        self.titreLineEdit.setPlaceholderText(_translate("MainWindow", "Les Lois de Newton"))
        self.soustitreGroupBox.setTitle(_translate("MainWindow", "Sous-Titre"))
        self.soustitreLineEdit.setPlaceholderText(_translate("MainWindow", "Newton, grand physicien"))
        self.matGroupBox.setTitle(_translate("MainWindow", "Matière"))
        self.matLineEdit.setPlaceholderText(_translate("MainWindow", "PHY"))
        self.matToolButton.setText(_translate("MainWindow", "↩"))
        self.numGroupBox.setTitle(_translate("MainWindow", "Numéro"))
        self.numLineEdit.setPlaceholderText(_translate("MainWindow", "0920"))
        self.numToolButton.setText(_translate("MainWindow", "↩"))
        self.sectionGroupBox.setTitle(_translate("MainWindow", "Première Section"))
        self.sectionNumLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">1.</span></p></body></html>"))
        self.sectionLineEdit.setPlaceholderText(_translate("MainWindow", "La Loi de l\'Inertie"))
        self.pathPathLabel.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://google.com\"><span style=\" font-size:11pt; text-decoration: underline; color:#000000;\">Aucun chemin de sauvegarde</span></a></p></body></html>"))
        self.infoPersoGroupBox.setToolTip(_translate("MainWindow", "Pour modifier les informations, veuillez aller dans le Configurateur"))
        self.infoPersoGroupBox.setTitle(_translate("MainWindow", "Informations Personnelles"))
        self.auteurPersoGroupBox.setTitle(_translate("MainWindow", "Auteur"))
        self.auteurPersoLabel.setText(_translate("MainWindow", "Auteur"))
        self.secPersoGroupBox.setTitle(_translate("MainWindow", "Secondaire"))
        self.secPersoLabel.setText(_translate("MainWindow", "Secondaire"))
        self.genPushButton.setText(_translate("MainWindow", "Générer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.genTab), _translate("MainWindow", "Générateur"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.genTab), _translate("MainWindow", "Créer un document"))
        self.infoPerso.setTitle(_translate("MainWindow", "Informations Personnelles"))
        self.auteurConfig.setTitle(_translate("MainWindow", "Auteur"))
        self.auteurLineEdit.setPlaceholderText(_translate("MainWindow", "Laurent Bourgon"))
        self.secConfig.setTitle(_translate("MainWindow", "Secondaire"))
        self.secLineEdit.setPlaceholderText(_translate("MainWindow", "Secondaire 5 - 2019-2020"))
        self.configSaveButton.setText(_translate("MainWindow", "Appliquer et Enregistrer"))
        self.matieresConfig.setTitle(_translate("MainWindow", "Matières Personnalisées"))
        item = self.matiereTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Matière"))
        item = self.matiereTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom Court"))
        item = self.matiereTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Chemin"))
        self.matiereTablePlus.setText(_translate("MainWindow", "+"))
        self.matiereTableMinus.setText(_translate("MainWindow", "-"))
        self.matiereTableReset.setText(_translate("MainWindow", "Réinitialiser"))
        self.matiereTableBrowse.setText(_translate("MainWindow", "Parcourir..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), _translate("MainWindow", "Configurateur"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.configTab), _translate("MainWindow", "Modifier les Informations"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">pyÉtude</span></p></body></html>"))
        self.versionLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">Version: </span></p></body></html>"))
        self.varVersionLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">[VERSION]</span></p></body></html>"))
        self.gitHubLabel.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/BourgonLaurent/pyEtude/blob/master/LICENSE\"><span style=\" text-decoration: underline\">© Laurent Bourgon Sous la license MIT</span></a></p><p><br/></p><p><a href=\"https://github.com/BourgonLaurent/pyEtude\"><span style=\" text-decoration: underline\">Projet GitHub</span></a></p><p><a href=\"https://github.com/BourgonLaurent/pyEtude#faq\"><span style=\" text-decoration: underline\">Vous avez un problème?</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutTab), _translate("MainWindow", "À Propos"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.aboutTab), _translate("MainWindow", "À Propos"))
